alias vi='vim'
alias cdc='cd /home/user/Documents/cTF'
alias server='sudo systemctl restart apache2 mysql'
alias up='sudo python3 -m http.server 80'
alias x='clear'
alias c='gcc'
alias p3='python3'
alias db='mysql -u user -p'
alias down='sudo systemctl stop'
alias gc='git clone'
alias try='sudo openvpn /opt/vpn/try.ovpn'
alias compress-pdf='gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dBATCH -dColorImageResolution=72 -sOutputFile='
alias ghidra='sudo /opt/ghidra_9.2.3_PUBLIC/ghidraRun'
alias htb='sudo openvpn /opt/vpn/htb.ovpn'
alias firefox='./opt/firefox/firefox'
